name: CI
on: 
  [push, pull_request]
jobs:
  build_amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13.1
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.1
      - name: Checkout source code from repo
        uses: actions/checkout@v2
      - name: Build
        run: go build -o ./dist/amd64/pestka ./src/main.go
  build_arm:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13.1
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.1
      - name: Checkout source code from repo
        uses: actions/checkout@v2
      - name: Build
        run: 	GOOS=linux GOARCH=arm GOARM=5 go build -o ./dist/arm/pestka ./src/main.go
  check_style:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13.1
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.1
      - name: Install golint
        run: go get -u golang.org/x/lint/golint
      - name: Add golint to PATH
        run: export PATH=$PATH:/usr/local/go/bin/
      - name: Checkout source code from repo
        uses: actions/checkout@v2
      - name: Check style with gofmt
        run: test -z $(gofmt -l ./src/)
      - name: Check style with golint
        run: golint -min_confidence 0 -set_exit_status ./src/...
  check_correctness:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13.1
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.1
      - name: Checkout source code from repo
        uses: actions/checkout@v2
      - name: Check correctness with go vet
        run: go vet ./src/...
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13.1
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.1
      - name: Checkout source code from repo
        uses: actions/checkout@v2
      - name: Run tests
        run: go test -v ./tests
        